"""Frozen row schemas for every JSONL/parquet artifact in the project.

These pydantic models are the contract between the data layer, the training/eval
stack, and the stats layer. Change them only with a design-doc update — every
downstream consumer validates against them (stats/R/01_schema_validate.R mirrors
the trial-table schema).

Namespaces (docs/TIER_MAPPING.md):
  * `condition`  — the NEW ladder L0/L1b/L1r/L2/S1/S2/H1, identical semantics in
    both languages, generated by src/obtune/obf/.
  * `tier_icse`  — the legacy Papers-1/3 ladder L0/L1/L1b/L2/L3 on the 350
    byte-identical ICSE rows; the only rows comparable to the human baselines.
"""
from __future__ import annotations

from typing import Union, Any, Literal, Optional

from pydantic import BaseModel, Field, field_validator

Condition = Literal["L0", "L1b", "L1r", "L2", "S1", "S2", "S3", "S4", "H1"]

#: Composite (stacked) conditions live in a SEPARATE namespace and are deliberately NOT added
#: to `Condition`. Keeping that Literal closed is what protects `paths.TRAINABLE_CONDITIONS`,
#: the router's 8-class head, `ALL_CONDITIONS` and the RQ1 transfer matrix from a namespace
#: they were never designed for — CLAUDE.md §3.1 mandates single-transform conditions, and
#: `tier_icse` is the precedent for a parallel namespace that coexists without contaminating
#: the ladder. Only the four fields that must CARRY a composite accept the union.
#:
#: Order matters: composition does not commute, so `C_S1_L1r` is a distinct code from
#: `C_L1r_S1` rather than a spelling of it.
CompositeCondition = Literal[
    "C_L1r_S1", "C_S1_L1r", "C_L1b_S1", "C_L2_S4", "C_L1r_S3", "C_S4_S3",
]

#: Anything that may appear as a variant/eval label, ladder or composite.
AnyCondition = Union[Condition, CompositeCondition]
TierICSE = Literal["L0", "L1", "L1b", "L2", "L3"]
Language = Literal["python", "javascript"]
Split = Literal["train", "val", "test"]


class InputCase(BaseModel):
    """One concrete invocation of a program's entry point."""

    args_repr: str  # e.g. "(3, [1, 2])" — literal argument tuple source text
    output_canon: str  # canonical output serialization (exec/canon contract)
    case_role: Literal["human", "seed", "generated", "gate"] = "generated"


class BaseProgram(BaseModel):
    """A base (L0-normalized) program in data/train/base/ or data/eval/testset/base/."""

    program_id: str  # globally unique, e.g. "apps_train_00123" / "dsA_Python_36"
    language: Language
    source: str  # provenance: apps | cruxeval | humaneval | mbpp | multipl_e | csn | transpiled | dataset_a | dataset_b
    provenance: Literal["curated", "transpiled", "synthetic"] = "curated"
    code: str  # L0-normalized text (comments/docstrings stripped, 4-space indent)
    entry_point: str  # function name to call
    cases: list[InputCase]  # 3–5 training/eval cases
    gate_inputs: list[InputCase] = Field(default_factory=list)  # ~20 fuzz cases for the semantic gate
    loc: int = 0
    meta: dict[str, Any] = Field(default_factory=dict)


class Variant(BaseModel):
    """One obfuscated variant of a base program (data/*/variants/<cond>/<lang>.jsonl)."""

    program_id: str
    condition: AnyCondition
    language: Language
    code: str
    entry_point: str  # post-transform name (L1b/L1r/L2 rename the entry fn)
    entry_point_parent: str  # the L0 name
    rename_map: dict[str, str] = Field(default_factory=dict)  # orig -> new (identifier conditions)
    transform_meta: dict[str, Any] = Field(default_factory=dict)  # seed, attempts, skipped_constructs, notes
    gate: dict[str, Any] = Field(default_factory=dict)  # validate.py verdict summary


class TrainPair(BaseModel):
    """A materialized SFT example (data/train/pairs/<cond>/<lang>.jsonl)."""

    item_id: str  # f"{program_id}::{condition}::{case_idx}"
    program_id: str
    program_group_id: str  # = program_id; split unit (never split by row)
    condition: AnyCondition
    language: Language
    code: str
    entry_point: str
    args_repr: str
    output_repr: str  # gold literal, exactly what the model must emit
    split: Split
    provenance: str = "curated"

    @field_validator("condition")
    @classmethod
    def _no_h1_pairs(cls, v: str) -> str:
        if v == "H1":
            raise ValueError("H1 must never be materialized as a training pair")
        return v


class EvalItem(BaseModel):
    """One test-set row (new-condition namespace) in data/eval/testset/variants/."""

    item_id: str
    program_id: str
    dataset: Literal["A", "B"]
    condition: AnyCondition
    language: Language
    code: str
    entry_point: str
    args_repr: str
    output_repr: str
    case_role: str = "generated"
    tier_icse: Optional[TierICSE] = None  # set only on legacy_icse rows
    meta: dict[str, Any] = Field(default_factory=dict)


class TrialRow(BaseModel):
    """One graded model trial — the atom of results/trials.parquet (stats contract).

    Mirrored by stats/R/01_schema_validate.R; keep field names in sync.
    """

    run_id: str
    run_ts: str
    seed: int
    #: `baselines` added 2026-08-13 for the zero-training comparators (ICL, symbolic
    #: normalization, 7B zero-shot). They need their own namespace because `main` already
    #: holds two never-pooled grids — `base__L0` is n=1670 (Grid A) and `base__S3` is n=176
    #: (Grid B) — so with `resume: true` a Grid B arm landing in `main` silently reuses a
    #: Grid A `base` cell and the delta is computed across different programs.
    # `phase` is also the top-level cell-path namespace (`eval_vllm.cell_dir`), so a run
    # that shares a phase AND a system name with another run shares its cell paths. Two
    # grids that alias that way silently resume each other's cells — see MASTER_REPORT
    # §12.1. `baselines_gridA` exists so the Grid A (`heldout`) baselines cannot collide
    # with the Grid B (`testset`) ones, which are both `baselines`. Adding a phase is a
    # SCHEMA change, not a config change: naming an unlisted phase in a config fails at
    # the first row written, i.e. after a full generation pass. `tests/test_baseline_configs.py`
    # asserts every committed config's phase is one this Literal accepts.
    phase: Literal["pilot", "main", "final", "baselines", "baselines_gridA", "grid_rq1_7b", "align_lam_sweep", "formatonly_fix", "basecheck", "rq1_generic", "loto_generic", "rq2_generic", "baselines_generic", "rank_generic", "extra_generic", "merge_sweep_generic", "mole_generic", "h1_codellama", "selfcons_generic", "trace_generic"]
    experiment_id: str
    base_model: str
    model_family: Literal["coder", "instruct"]
    adapter_id: Optional[str]  # None = untuned base
    adapter_arch: Literal[
        "none", "oracle_prompt", "mono", "per_type", "router", "oracle_route",
        "merge_linear", "merge_ties", "merge_dare_ties", "merge_dare_linear", "knockout",
        # Activation-space mixtures (Part III). These get their OWN arch strings and never
        # reuse "router": stats/R/03_rq1_transfer.R selects the RQ1 matrix with
        # `adapter_arch == "per_type"`, and grid_v1.yaml records that mislabelling an RQ2
        # upper-bound system once swept it into the RQ1 headline. All four run on the HF
        # engine — vLLM applies exactly one adapter per request, so a per-token blend is
        # not expressible there at any max_lora_rank.
        "mole_router",       # the experiment: learned attention over experts
        "mole_uniform",      # the PRIMARY fixed-mixture contrast — differs in weights alone
        "mole_random",       # gate frozen at random init; if router ~= random, the gain is
                             # rank-256 residency, not routing
        "mole_hardrouter",   # the trained router's one-hot, through the mixture module
        # Weight-space invariance (Phase 2). Trained with L_task + lambda * L_align, where
        # L_align pulls the student's answer-position hidden states on OBFUSCATED code toward
        # a frozen tuned_L0 teacher's states on the CLEAN parent. Its own arch string for the
        # same reason the mole_* family got theirs: the RQ1 matrix is selected by
        # `adapter_arch == "per_type"`, and an invariance arm is not a per-condition
        # specialist even though it trains on one condition.
        "invariance",
        # The control that decides whether a positive `invariance` result means anything:
        # identical objective, teacher states drawn from a DIFFERENT program. If this matches
        # the matched teacher, L_align is a regularizer and the interpretation collapses. It
        # is a separate arch, not a flag, so it can never be pooled with the real arm by a
        # groupby that forgot about it -- the mole_random lesson.
        "invariance_mismatch",
    ]
    train_cond: Optional[str]  # None | condition | "mix"
    eval_cond: AnyCondition
    language: Language
    dataset: Literal["A", "B"]
    snippet_id: str  # program_id
    item_id: str
    is_core: int = 1
    h1_access_purpose: Optional[Literal["pilot_eval", "final_eval"]] = None
    prompt_id: str = "base_v1"
    output_raw: str = ""
    output_parsed: Optional[str] = None
    correct: int = 0
    parse_ok: int = 1
    grade_method: Literal["exact", "normalized", "manual"] = "normalized"
    error_category: Optional[str] = None
    n_gen_tokens: int = 0
    gpu_id: Optional[str] = None
    config_sha: Optional[str] = None
    script_sha: Optional[str] = None

    @field_validator("h1_access_purpose")
    @classmethod
    def _h1_purpose_required(cls, v, info):
        if info.data.get("eval_cond") == "H1" and v is None:
            raise ValueError("H1 trials must record h1_access_purpose (pilot_eval|final_eval)")
        return v
