"""Frozen row schemas for every JSONL/parquet artifact in the project.

These pydantic models are the contract between the data layer, the training/eval
stack, and the stats layer. Change them only with a design-doc update — every
downstream consumer validates against them (stats/R/01_schema_validate.R mirrors
the trial-table schema).

Namespaces (docs/TIER_MAPPING.md):
  * `condition`  — the NEW ladder L0/L1b/L1r/L2/S1/S2/H1, identical semantics in
    both languages, generated by src/obtune/obf/.
  * `tier_icse`  — the legacy Papers-1/3 ladder L0/L1/L1b/L2/L3 on the 350
    byte-identical ICSE rows; the only rows comparable to the human baselines.
"""
from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel, Field, field_validator

Condition = Literal["L0", "L1b", "L1r", "L2", "S1", "S2", "H1"]
TierICSE = Literal["L0", "L1", "L1b", "L2", "L3"]
Language = Literal["python", "javascript"]
Split = Literal["train", "val", "test"]


class InputCase(BaseModel):
    """One concrete invocation of a program's entry point."""

    args_repr: str  # e.g. "(3, [1, 2])" — literal argument tuple source text
    output_canon: str  # canonical output serialization (exec/canon contract)
    case_role: Literal["human", "seed", "generated", "gate"] = "generated"


class BaseProgram(BaseModel):
    """A base (L0-normalized) program in data/train/base/ or data/eval/testset/base/."""

    program_id: str  # globally unique, e.g. "apps_train_00123" / "dsA_Python_36"
    language: Language
    source: str  # provenance: apps | cruxeval | humaneval | mbpp | multipl_e | csn | transpiled | dataset_a | dataset_b
    provenance: Literal["curated", "transpiled", "synthetic"] = "curated"
    code: str  # L0-normalized text (comments/docstrings stripped, 4-space indent)
    entry_point: str  # function name to call
    cases: list[InputCase]  # 3–5 training/eval cases
    gate_inputs: list[InputCase] = Field(default_factory=list)  # ~20 fuzz cases for the semantic gate
    loc: int = 0
    meta: dict[str, Any] = Field(default_factory=dict)


class Variant(BaseModel):
    """One obfuscated variant of a base program (data/*/variants/<cond>/<lang>.jsonl)."""

    program_id: str
    condition: Condition
    language: Language
    code: str
    entry_point: str  # post-transform name (L1b/L1r/L2 rename the entry fn)
    entry_point_parent: str  # the L0 name
    rename_map: dict[str, str] = Field(default_factory=dict)  # orig -> new (identifier conditions)
    transform_meta: dict[str, Any] = Field(default_factory=dict)  # seed, attempts, skipped_constructs, notes
    gate: dict[str, Any] = Field(default_factory=dict)  # validate.py verdict summary


class TrainPair(BaseModel):
    """A materialized SFT example (data/train/pairs/<cond>/<lang>.jsonl)."""

    item_id: str  # f"{program_id}::{condition}::{case_idx}"
    program_id: str
    program_group_id: str  # = program_id; split unit (never split by row)
    condition: Condition
    language: Language
    code: str
    entry_point: str
    args_repr: str
    output_repr: str  # gold literal, exactly what the model must emit
    split: Split
    provenance: str = "curated"

    @field_validator("condition")
    @classmethod
    def _no_h1_pairs(cls, v: str) -> str:
        if v == "H1":
            raise ValueError("H1 must never be materialized as a training pair")
        return v


class EvalItem(BaseModel):
    """One test-set row (new-condition namespace) in data/eval/testset/variants/."""

    item_id: str
    program_id: str
    dataset: Literal["A", "B"]
    condition: Condition
    language: Language
    code: str
    entry_point: str
    args_repr: str
    output_repr: str
    case_role: str = "generated"
    tier_icse: Optional[TierICSE] = None  # set only on legacy_icse rows
    meta: dict[str, Any] = Field(default_factory=dict)


class TrialRow(BaseModel):
    """One graded model trial — the atom of results/trials.parquet (stats contract).

    Mirrored by stats/R/01_schema_validate.R; keep field names in sync.
    """

    run_id: str
    run_ts: str
    seed: int
    phase: Literal["pilot", "main", "final"]
    experiment_id: str
    base_model: str
    model_family: Literal["coder", "instruct"]
    adapter_id: Optional[str]  # None = untuned base
    adapter_arch: Literal[
        "none", "oracle_prompt", "mono", "per_type", "router", "merge_linear",
        "merge_ties", "merge_dare_ties", "merge_dare_linear", "knockout",
    ]
    train_cond: Optional[str]  # None | condition | "mix"
    eval_cond: Condition
    language: Language
    dataset: Literal["A", "B"]
    snippet_id: str  # program_id
    item_id: str
    is_core: int = 1
    h1_access_purpose: Optional[Literal["pilot_eval", "final_eval"]] = None
    prompt_id: str = "base_v1"
    output_raw: str = ""
    output_parsed: Optional[str] = None
    correct: int = 0
    parse_ok: int = 1
    grade_method: Literal["exact", "normalized", "manual"] = "normalized"
    error_category: Optional[str] = None
    n_gen_tokens: int = 0
    gpu_id: Optional[str] = None
    config_sha: Optional[str] = None
    script_sha: Optional[str] = None

    @field_validator("h1_access_purpose")
    @classmethod
    def _h1_purpose_required(cls, v, info):
        if info.data.get("eval_cond") == "H1" and v is None:
            raise ValueError("H1 trials must record h1_access_purpose (pilot_eval|final_eval)")
        return v
