#!/usr/bin/env python3
"""Assemble the pipeline's analysis JSONs into one dated markdown report.

    python scripts/pipeline/report.py            # -> results/analysis/pipeline_report_<date>.md
    python scripts/pipeline/run.py --report      # same, after a state sync

Reads every stage in plan.yaml that declares `report_json`; a missing file is reported as
PENDING, never invented. Verdicts come from the analysis scripts (which apply the rules frozen
in CLAUDE_SCRATCHPAD.md); this file only formats them.
"""
from __future__ import annotations

import datetime as dt
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
PLAN = ROOT / "scripts" / "pipeline" / "plan.yaml"
STATE = ROOT / "runs" / "pipeline" / "state.json"
OUT_DIR = ROOT / "results" / "analysis"

ICON = {"CONFIRMED": "✅", "REFUTED": "❌", "PARTIAL": "◐", "INCONCLUSIVE": "▫", "PENDING": "⏳", "REPORTED": "📎"}


def _fmt_contrast(c: dict) -> str:
    star = "\\*" if c.get("excludes_zero") else ""
    eq = " ≡" if c.get("equivalent") else ""
    return f"{c['value_pts']:+.2f} [{c['ci_lo']:+.2f}, {c['ci_hi']:+.2f}]{star}{eq}"


def write_report(plan: dict, st: dict) -> str:
    today = dt.date.today().isoformat()
    lines = [f"# Pipeline report — {today}", "",
             "Generated by `scripts/pipeline/report.py` from the analysis JSONs under "
             "`results/analysis/pipeline/`. Verdicts apply the rules pre-registered in "
             "`CLAUDE_SCRATCHPAD.md` (2026-09-07); nothing here read H1. "
             "`*` = 95% program-clustered bootstrap interval excludes zero; `≡` = TOST-equivalent at the stated margin.", ""]
    # stage table
    lines += ["## Stages", "", "| stage | rq | job | status | slurm |", "|---|---|---|---|---|"]
    for s in plan["stages"]:
        r = st.get("stages", {}).get(s["name"], {})
        en = "" if s.get("enabled", True) else " (disabled)"
        lines.append(f"| {s['name']}{en} | {s.get('rq', '')} | {r.get('job_id', '')} | {r.get('status', '-')} | {r.get('slurm_state', '')} |")
    ext = st.get("external", {})
    if ext:
        lines += ["", "External jobs: " + ", ".join(f"`{k}`={v}" for k, v in ext.items())]
    lines.append("")
    # verdicts by RQ
    by_rq: dict[str, list] = {}
    for s in plan["stages"]:
        rj = s.get("report_json")
        if not rj:
            continue
        p = ROOT / rj
        if not p.exists():
            by_rq.setdefault(s.get("rq", "?"), []).append((s["name"], None))
            continue
        by_rq.setdefault(s.get("rq", "?"), []).append((s["name"], json.loads(p.read_text())))
    lines += ["## Verdicts", ""]
    for rq in sorted(by_rq):
        lines += [f"### {rq}", ""]
        for name, res in by_rq[rq]:
            if res is None:
                lines.append(f"- ⏳ `{name}` — PENDING (no analysis output yet)")
                continue
            hyps = res.get("hypotheses") or [{"id": k, "rule": "", "verdict": v, "evidence": ""}
                                             for k, v in (res.get("verdicts") or {}).items()]
            if not hyps:
                lines.append(f"- 📎 `{name}` — ran, no hypothesis block")
            for h in hyps:
                ic = ICON.get(h["verdict"], "•")
                ev = f" — {h['evidence']}" if h.get("evidence") else ""
                rule = f" *(rule: {h['rule']})*" if h.get("rule") else ""
                lines.append(f"- {ic} **{h['id']}**: {h['verdict']}{ev}{rule}  ·  `{name}`")
        lines.append("")
    # accuracy tables + contrasts per analysis
    lines += ["## Tables", ""]
    for rq in sorted(by_rq):
        for name, res in by_rq[rq]:
            if res is None:
                continue
            lines += [f"### `{name}`", ""]
            acc = res.get("accuracy") or {}
            # two shapes: {model: {system: {cond: acc}}} (cellkit) or {system: {cond: acc}} (35_composites)
            models = acc if acc and isinstance(next(iter(acc.values()), {}), dict) and \
                any(isinstance(v2, dict) for v in acc.values() for v2 in v.values()) else {res.get("model", ""): acc}
            for m, table in models.items():
                if not table:
                    continue
                conds = sorted({c for row in table.values() for c in row}, key=lambda c: (c == "pooled", c))
                lines += [f"**{m}** — accuracy", "", "| system | " + " | ".join(conds) + " |",
                          "|---|" + "---|" * len(conds)]
                for sysname, row in table.items():
                    lines.append(f"| {sysname} | " + " | ".join(
                        f"{row[c]:.4f}" if c in row and isinstance(row[c], (int, float)) else "" for c in conds) + " |")
                lines.append("")
            contrasts = res.get("contrasts") or {}
            if contrasts and not isinstance(next(iter(contrasts.values())), dict) or "pooled" in res:
                contrasts = {res.get("model", ""): res.get("pooled", {})}
            for m, cs in contrasts.items():
                if not cs:
                    continue
                lines += [f"**{m}** — contrasts (pts)", "", "| contrast | Δ [95% CI] | n_prog |", "|---|---|---|"]
                for lab, c in cs.items():
                    if isinstance(c, dict) and "value_pts" in c:
                        lines.append(f"| {lab} | {_fmt_contrast(c)} | {c.get('n_programs', '')} |")
                lines.append("")
            for fam, f in (res.get("families") or {}).items():
                lines += [f"**FDR family `{fam}`** — {f['n_survive']}/{f['n_tests']} survive q<0.05 (control {f['control']})", "",
                          "| system | cond | Δ | 95% CI | p | q |", "|---|---|---|---|---|---|"]
                for r in f["rows"]:
                    lines.append(f"| {r['system']} | {r['cond']} | {r['delta_pts']:+.2f} | [{r['ci_lo']:+.2f}, {r['ci_hi']:+.2f}] | {r['p_boot']:.4f} | {r['q_bh']:.4f}{' ✓' if r['survives_fdr'] else ''} |")
                lines.append("")
            if res.get("knockout"):
                lines += ["| system | mean Δlogp (knockout − clean) | n |", "|---|---|---|"]
                for sname, summ in res["knockout"].items():
                    lines.append(f"| {sname} | {summ['mean_delta_logp']:+.4f} | {summ['n_items']} |")
                lines.append("")
                for lab, r in (res.get("paired") or {}).items():
                    lines.append(f"- paired {lab}: {r['value']:+.4f} [{r['ci_lo']:+.4f}, {r['ci_hi']:+.4f}]{'*' if r['excludes_zero'] else ''}")
                lines.append("")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / f"pipeline_report_{today}.md"
    out.write_text("\n".join(lines))
    return f"wrote {out}"


def main() -> int:
    plan = yaml.safe_load(PLAN.read_text())
    st = json.loads(STATE.read_text()) if STATE.exists() else {"stages": {}}
    print(write_report(plan, st))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
