"""Specialist-update geometry, pooled to a per-model table (user request item 10).

Consumes the per-model JSONs written by 75_specialist_geometry.py and emits
paper/router_merger/tables/specialist_geometry.tex.

The comparison that carries the result is `clean` against `within`. If the clean-code
specialist occupied a direction the obfuscation specialists do not span, removing it
from the merge would cost forward accuracy. It does not (76_merge_ablation), and this
says why: L0's mean cosine to the five obfuscation specialists is indistinguishable
from the identifier-identifier and structural-structural pairs.
"""
from __future__ import annotations
import json, statistics as st
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT/"results/analysis/pipeline"
MODELS = ["codellama-7b","codellama-13b","codellama-34b","llama31-8b",
          "starcoder2-15b","gemma3-12b","codegemma-7b","granite31-8b"]
NICE = {"codellama-7b":"CodeLlama-7B","codellama-13b":"CodeLlama-13B",
        "codellama-34b":"CodeLlama-34B","llama31-8b":"Llama-3.1-8B",
        "starcoder2-15b":"StarCoder2-15B","gemma3-12b":"Gemma-3-12B",
        "codegemma-7b":"CodeGemma-7B","granite31-8b":"Granite-3.1-8B"}
KINDS = [("within","within family"),("across","across family"),("clean","L0 vs obf.")]

def main() -> int:
    rows, got = [], 0
    for m in MODELS:
        f = SRC/f"specialist_geometry_{m}.json"
        if not f.exists():
            rows.append((NICE[m], None)); continue
        d = json.loads(f.read_text()); got += 1
        cells = {}
        for k, _ in KINDS:
            g = [r for r in d if r["kind"] == k]
            cells[k] = None if not g else (
                st.mean(r["cosine"] for r in g),
                st.mean(r["overlap"] for r in g),
                st.mean(r["sign_agree"] for r in g))
        rows.append((NICE[m], cells))

    L = [r"% GENERATED by scripts/analysis/77_geometry_table.py -- do not edit by hand.",
         r"\begin{table}[t]", r"\centering\small\setlength{\tabcolsep}{4pt}",
         r"\caption{\textbf{Geometry of the specialist updates.} Mean pairwise cosine "
         r"similarity ($\cos$) between task vectors $\Delta = sBA$, fraction of "
         r"magnitude-trimmed coordinates two specialists share ($\cap$), and sign agreement "
         r"on those shared coordinates ($\pm$), at the density used for merging. Pairs are "
         r"grouped as identifier--identifier and structural--structural (\emph{within}), "
         r"identifier--structural (\emph{across}), and the clean-code specialist against each "
         r"of the five obfuscation specialists (\emph{L0 vs obf.}). \textbf{The last group "
         r"matches the first}: \texttt{L0} occupies no direction the obfuscation specialists "
         r"do not already span, which is why removing it from the merge costs no forward "
         r"accuracy (Section~\ref{sec:rq1}). Computed from adapter weights alone.}",
         r"\label{tab:geometry}",
         r"\begin{tabular}{@{}l" + "ccc"*len(KINDS) + r"@{}}", r"\toprule",
         " & " + " & ".join(rf"\multicolumn{{3}}{{c}}{{\textbf{{{lab}}}}}" for _, lab in KINDS) + r" \\",
         "".join(rf"\cmidrule(lr){{{2+3*i}-{4+3*i}}}" for i in range(len(KINDS))),
         "model & " + " & ".join(r"$\cos$ & $\cap$ & $\pm$" for _ in KINDS) + r" \\",
         r"\midrule"]
    for name, cells in rows:
        if cells is None:
            L.append(name + " & " + " & ".join([r"\texttt{--}"]*(3*len(KINDS))) + r" \\"); continue
        out = []
        for k, _ in KINDS:
            v = cells[k]
            out += [r"\texttt{--}"]*3 if v is None else [f"{v[0]:.2f}", f"{v[1]:.2f}", f"{v[2]:.2f}"]
        L.append(name + " & " + " & ".join(out) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]

    out = ROOT/"paper/router_merger/tables/specialist_geometry.tex"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out}  ({got}/{len(MODELS)} models present)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
