"""Cross-language transfer: Python-trained adapters evaluated on JavaScript (user item 9).

Forward only. JavaScript backward grading executes the predicted input through
obtune.exec.pool, which needs `node`; juno has none. Forward grading is a JSON parse
against the precomputed output_repr, so it needs no interpreter. See
configs/eval/crosslang_fwd.yaml.

Reports each arm as a percentage of the UNTUNED model's accuracy on clean JavaScript,
the same reference the Python tables use, so the recovery claim can be compared across
languages directly. Paired program-clustered bootstrap for the contrasts.
"""
from __future__ import annotations
import sys, json
from pathlib import Path
import numpy as np, pandas as pd
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT/"scripts/analysis"))
from cellkit import load_cell

JS, PY = "javascript", "python"
XPH = ["crosslang_generic"]
PYPH = ["panel_core","composite_generic","composite_depth","f2_divergence","merge_panel",
        "mole_generic","rq2_generic"]
MODELS = ["codellama-7b","codellama-13b","llama31-8b","granite31-8b"]
NICE = {"codellama-7b":"CodeLlama-7B","codellama-13b":"CodeLlama-13B",
        "llama31-8b":"Llama-3.1-8B","granite31-8b":"Granite-3.1-8B"}
ARMS = [("base","base"),("tuned_L0","clean"),("mono_all","breadth"),("merge_dare_ties","merge")]
GROUPS = [("L0", ["L0"]),
          ("singles", ["L1b","L1r","L2","S1","S2"]),
          ("d2 seen", ["C_L1b_S1","C_L1r_S1","C_S1_L1r","C_L2_S4","C_L1r_S3","C_S4_S3"])]

# --------------------------------------------------------------------- contamination
# CruxEval-X is a PORT: `cruxevalx_js_N` is the same program as `cruxeval_sample_N` with
# the same arguments and the same expected output, and `humaneval_js_N` pairs with
# `humaneval_py_N`. Verified by reading a pair side by side (cruxevalx_js_14 /
# cruxeval_sample_14: reverse a stripped string, args ("   OOP   ",), output "POO").
#
# 87 of the 168 JavaScript evaluation programs have their Python twin in the Python
# TRAIN split. For those, an adapter can reproduce a memorised program->output pair
# rather than read the JavaScript, so they cannot support a transfer claim. The default
# here is therefore the 81-program uncontaminated subset.
_TWIN = {"cruxevalx": "cruxeval_sample_{n}", "humaneval": "humaneval_py_{n}"}

def _python_training_ids():
    """Programs actually TRAINED on, from the split assignment.

    Not the contents of data/train/**/python.jsonl: that tree is the full pool, and the
    train/val/test partition lives in data/splits/python.json. Reading the pool treats
    every program as trained-on and over-filters -- it left 43 programs here where the
    correct answer is 81.
    """
    asg = json.loads((ROOT/"data/splits/python.json").read_text())["assignment"]
    return {k for k, v in asg.items() if v == "train"}

def _twin(sid):
    import re
    m = re.match(r"^(.*?)_js_(\d+)$", str(sid))
    if not m: return None
    t = _TWIN.get(m.group(1))
    return None if t is None else t.format(n=m.group(2))

_PYIDS = None
def contaminated(sid):
    global _PYIDS
    if _PYIDS is None: _PYIDS = _python_training_ids()
    t = _twin(sid)
    return t is not None and t in _PYIDS


def pool(ph, m, arm, cs, lang, clean=True):
    fr = []
    for c in cs:
        d = load_cell(ph, m, arm, c, language=lang)
        if d is None or d.format_fail.mean() > 0.25: continue
        if clean and lang == JS:
            d = d[~d.snippet_id.map(contaminated)]
            if d.empty: continue
        fr.append(d)
    return pd.concat(fr) if fr else None

def acc(ph, m, arm, cs, lang, clean=True):
    d = pool(ph, m, arm, cs, lang, clean); return None if d is None else float(d.correct.mean())

def contrast(m, a, b, cs, lang, ph, n=2000, clean=True):
    A, B = pool(ph, m, a, cs, lang, clean), pool(ph, m, b, cs, lang, clean)
    if A is None or B is None: return None
    ps = sorted(set(A.snippet_id) & set(B.snippet_id))
    if not ps: return None
    ga = {p: g.correct.to_numpy(float) for p, g in A.groupby("snippet_id") if p in ps}
    gb = {p: g.correct.to_numpy(float) for p, g in B.groupby("snippet_id") if p in ps}
    pt = (np.concatenate([ga[p] for p in ps]).mean() - np.concatenate([gb[p] for p in ps]).mean())*100
    rng = np.random.default_rng(17); idx = np.arange(len(ps))
    dr = [(np.concatenate([ga[ps[j]] for j in pk]).mean() - np.concatenate([gb[ps[j]] for j in pk]).mean())*100
          for pk in (rng.choice(idx, len(ps), True) for _ in range(n))]
    lo, hi = np.percentile(dr, [2.5, 97.5]); return pt, lo, hi


def _tex(out):
    """The cross-language table: every arm as a percentage of untuned clean JavaScript."""
    cols = ["base", "clean", "breadth", "merge"]
    L = [r"% GENERATED by scripts/analysis/78_crosslang.py -- do not edit by hand.",
         r"\begin{table}[t]", r"\centering\small\setlength{\tabcolsep}{4pt}",
         r"\caption{\textbf{Cross-language transfer.} Every adapter is trained on \textbf{Python} "
         r"and evaluated here on \textbf{JavaScript}, forward only. Cells are a percentage of the "
         r"untuned model's accuracy on clean JavaScript, the same form of reference as "
         r"Table~\ref{tab:main}. \textbf{Every adapted arm reading obfuscated JavaScript exceeds "
         r"the untuned model reading clean JavaScript}, on every condition group and all four "
         r"models, without any adapter having seen JavaScript. No arm transfers reliably better "
         r"than another: pooled training exceeds the merge on two models and is null on two. "
         r"The held-out obfuscator family has no JavaScript "
         r"variant and is therefore absent. Backward is not reported: grading it executes the "
         r"predicted input, and our cluster has no JavaScript runtime. "
         r"\\textbf{Restricted to the 81 of 168 evaluation programs whose Python twin is absent "
         r"from training}: CruxEval-X and HumanEval-X are ports, so the remaining 87 programs "
         r"appear in Python training with identical arguments and outputs and cannot support a "
         r"transfer claim.}",
         r"\label{tab:crosslang}",
         r"\begin{tabular}{@{}ll" + "r"*len(cols) + r"@{}}", r"\toprule",
         r"model & group & " + " & ".join(cols) + r" \\", r"\midrule"]
    first = True
    for name, rec in out.items():
        if not first: L.append(r"\addlinespace")
        first = False
        for gi, (g, _) in enumerate(GROUPS):
            gr = rec["groups"].get(g, {})
            vals = []
            for c in cols:
                v = gr.get(c)
                vals.append(r"\texttt{--}" if v is None else f"{v:.0f}")
            lead = rf"\multirow{{{len(GROUPS)}}}{{*}}{{{name}}}" if gi == 0 else ""
            L.append(f"{lead} & {g} & " + " & ".join(vals) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    f = ROOT/"paper/router_merger/tables/crosslang.tex"
    f.write_text("\n".join(L) + "\n")
    print(f"wrote {f}")


def main() -> int:
    out = {}
    for m in MODELS:
        ref_js = acc(XPH, m, "base", ["L0"], JS)
        if ref_js is None:
            print(f"{NICE[m]}: no JavaScript cells yet\n"); continue
        ref_py = acc(PYPH, m, "base", ["L0"], PY)
        print(f"=== {NICE[m]} ===")
        npg = pool(XPH, m, "base", ["L0"], JS).snippet_id.nunique()
        print(f"[{npg} uncontaminated programs of 168; the rest have a Python twin in training]")
        print(f"untuned clean-code accuracy: JavaScript {ref_js:.3f}"
              + (f", Python {ref_py:.3f}" if ref_py else ", Python --"))
        print("\n% of the untuned model's clean-JavaScript accuracy "
              "(Python-trained adapters, JavaScript items)\n")
        print(f"{'group':10s} " + " ".join(f"{n:>9s}" for _, n in ARMS))
        rec = {}
        for g, cs in GROUPS:
            row, gr = [], {}
            for a, n in ARMS:
                v = acc(XPH, m, a, cs, JS)
                gr[n] = None if v is None else round(v/ref_js*100, 2)
                row.append("       --" if v is None else f"{v/ref_js*100:8.0f}%")
            rec[g] = gr
            print(f"{g:10s} " + " ".join(row))
        out[NICE[m]] = {"ref_js": round(ref_js, 4),
                        "ref_py": None if ref_py is None else round(ref_py, 4), "groups": rec}
        print("\npaired contrasts on JavaScript (95% CI, program-clustered, 2000 resamples)\n")
        cons = [("breadth - base", "mono_all", "base"),
                ("merge - base", "merge_dare_ties", "base"),
                ("clean - base", "tuned_L0", "base"),
                ("breadth - merge", "mono_all", "merge_dare_ties")]
        cr = {}
        for lab, a, b in cons:
            r = contrast(m, a, b, [c for _, cs in GROUPS for c in cs], JS, XPH)
            cr[lab] = None if r is None else dict(delta=round(r[0],2), lo=round(r[1],2), hi=round(r[2],2))
            f = "      --      " if r is None else \
                f"{r[0]:+6.2f} [{r[1]:+5.1f},{r[2]:+5.1f}]{'*' if (r[1]>0)==(r[2]>0) else ' '}"
            print(f"  {lab:18s} {f}")
        out[NICE[m]]["contrasts"] = cr
        print()
    _tex(out)
    f = ROOT/"results/analysis/pipeline/crosslang.json"
    f.write_text(json.dumps(out, indent=2)); print(f"wrote {f}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
