#!/usr/bin/env python
"""B7: what each arm actually costs to deploy.

    python scripts/analysis/80_deployment_cost.py <model>

The paper's defence against the router is that the merge is cheaper to deploy. That claim
currently carries no number. This measures three, per arm, on one GPU:

  stored parameters   trainable parameters shipped alongside the base model
  peak memory         torch.cuda.max_memory_allocated across a fixed decode workload
  throughput          generated tokens per second on that same workload

Arms: untuned, a single LoRA, the six-way merge, and the router. The router's cost is the
point of the table -- it must hold every expert resident and run a gate per token, where the
merge ships ONE adapter the same size as a single LoRA. Measured, not asserted.

Identical prompts, identical decode settings, identical token budget for every arm, so the
only difference is the arm. Greedy, as every eval here is.
"""
from __future__ import annotations
import sys, json, time, gc
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT/"src"))

N_PROMPTS, MAX_NEW = 32, 64
N_WARM, N_TIMED = 3, 3
EXPERTS = ["L0", "L1b", "L1r", "L2", "S1", "S2", "S3", "S4"]
SHORT = {"codellama-7b": "codellama7b", "codellama-13b": "codellama13b",
         "codellama-34b": "codellama34b", "llama31-8b": "llama318b",
         "granite31-8b": "granite318b", "codegemma-7b": "codegemma7b",
         "gemma3-12b": "gemma312b", "starcoder2-15b": "starcoder215b"}

def _params(d: Path) -> int:
    from safetensors.torch import load_file
    f = d/"adapter_model.safetensors"
    if not f.exists(): return 0
    return sum(t.numel() for t in load_file(str(f)).values())

NICE = {"codellama-7b": "CodeLlama-7B", "llama31-8b": "Llama-3.1-8B",
        "codellama-13b": "CodeLlama-13B", "codellama-34b": "CodeLlama-34B",
        "granite31-8b": "Granite-3.1-8B", "codegemma-7b": "CodeGemma-7B",
        "gemma3-12b": "Gemma-3-12B", "starcoder2-15b": "StarCoder2-15B"}
ROWS = [("untuned", r"\emph{untuned}"), ("single LoRA", "single LoRA"),
        ("merge", "merge"), ("router", "router")]


def _tex(models: list[str]) -> None:
    """Emit the cost table from the per-model JSONs this script already wrote.

    Reads rather than recomputes: the measurement needs a GPU and a fixed decode workload,
    and re-running it to typeset it would change the numbers by whatever the node was doing
    at the time. `--tex` is therefore a separate, GPU-free entry point.
    """
    recs = {}
    for m in models:
        f = ROOT/f"results/analysis/pipeline/deployment_cost_{m}.json"
        if f.exists():
            recs[m] = json.loads(f.read_text())
        else:
            print(f"  MISSING INPUT: {f.relative_to(ROOT)}")
    if not recs:
        print("no deployment-cost JSON found; nothing to emit"); return
    ms = [m for m in models if m in recs]
    L = [r"% GENERATED by scripts/analysis/80_deployment_cost.py --tex -- do not edit by hand.",
         r"\begin{table}[t]", r"\centering\small\setlength{\tabcolsep}{5pt}",
         r"\caption{\textbf{What each arm costs to deploy.} Parameters shipped alongside the "
         r"base model, peak allocated memory, and greedy decode throughput on an identical "
         r"workload (" + str(recs[ms[0]].get("untuned", {}).get("n_prompts", "")) +
         r" prompts, " + str(recs[ms[0]].get("untuned", {}).get("max_new", "")) +
         r" new tokens, one GPU). \textbf{The router's cost is storage, not speed}: it must "
         r"hold eight experts resident and runs a gate per token, which is $8\times$ the "
         r"parameters of the merge and a little more memory, but throughput is within noise of "
         r"a single adapter. The merge ships \emph{one} adapter the size of a single LoRA. "
         r"Decode is slower for every adapted arm than for the untuned model because the LoRA "
         r"path is not fused here; that cost is shared by all of them and is not what "
         r"distinguishes the arms.}",
         r"\label{tab:deploycost}",
         r"\begin{tabular}{@{}l" + ("rrr" * len(ms)) + r"@{}}", r"\toprule",
         " & " + " & ".join(r"\multicolumn{3}{c}{\textbf{%s}}" % NICE.get(m, m) for m in ms) + r" \\",
         " ".join(r"\cmidrule(lr){%d-%d}" % (2 + 3*i, 4 + 3*i) for i in range(len(ms))),
         "arm & " + " & ".join(r"params & GB & tok/s" for _ in ms) + r" \\",
         r"\midrule"]
    for key, lab in ROWS:
        cells = [lab]
        for m in ms:
            d = recs[m].get(key) or {}
            pr = d.get("stored_params")
            cells += [
                r"\texttt{--}" if pr is None else ("0" if pr == 0 else f"{pr/1e6:.0f}M"),
                r"\texttt{--}" if d.get("peak_mem_gb") is None else f"{d['peak_mem_gb']:.2f}",
                r"\texttt{--}" if d.get("tokens_per_s") is None else f"{d['tokens_per_s']:.0f}",
            ]
        L.append(" & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    f = ROOT/"paper/router_merger/tables/deployment_cost.tex"
    f.write_text("\n".join(L) + "\n")
    print(f"wrote {f}")


def main() -> int:
    # GPU-free path: typeset what has already been measured.
    if "--tex" in sys.argv:
        _tex(list(SHORT)); return 0
    import torch, yaml
    from transformers import AutoModelForCausalLM, AutoTokenizer
    m = sys.argv[1] if len(sys.argv) > 1 else "codellama-7b"
    reg = yaml.safe_load((ROOT/"configs/models.yaml").read_text()); reg = reg.get("models", reg)
    base_id = reg[m]["hf_id"]
    root = ROOT/f"runs/adapters/{m}/python"

    arms = [("untuned", None),
            ("single LoRA", root/"L0_r32_s17"/"best"),
            ("merge", root/"merge_dare_ties_r32_s17")]
    tok = AutoTokenizer.from_pretrained(base_id)
    if tok.pad_token is None: tok.pad_token = tok.eos_token
    prompts = ["def f(x):\n    return x * 2\n\n# f(21) returns"] * N_PROMPTS
    enc = tok(prompts, return_tensors="pt", padding=True).to("cuda")

    def timed(model):
        """Median of N_TIMED runs after N_WARM warm-ups.

        A single warm-up is not enough: the FIRST arm measured pays one-off CUDA context and
        autotuning costs, which made the untuned model read 489 tok/s against 1045 for both
        adapter arms -- i.e. adding an adapter appeared to double throughput. Warming properly
        and taking a median removes it.
        """
        import statistics
        with torch.no_grad():
            for _ in range(N_WARM):
                model.generate(**enc, max_new_tokens=8, do_sample=False)
        rates = []
        for _ in range(N_TIMED):
            torch.cuda.synchronize(); t0 = time.perf_counter()
            with torch.no_grad():
                g = model.generate(**enc, max_new_tokens=MAX_NEW, do_sample=False)
            torch.cuda.synchronize(); dt = time.perf_counter() - t0
            rates.append(int((g.shape[1] - enc["input_ids"].shape[1]) * g.shape[0]) / dt)
        return statistics.median(rates)

    out = {}
    for name, adapter in arms:
        gc.collect(); torch.cuda.empty_cache(); torch.cuda.reset_peak_memory_stats()
        model = AutoModelForCausalLM.from_pretrained(base_id, dtype=torch.bfloat16, device_map="cuda")
        if adapter is not None:
            from peft import PeftModel
            model = PeftModel.from_pretrained(model, str(adapter))
        model.eval()
        out[name] = dict(stored_params=_params(adapter) if adapter else 0,
                         peak_mem_gb=round(torch.cuda.max_memory_allocated()/2**30, 2),
                         tokens_per_s=round(timed(model), 1), n_prompts=N_PROMPTS, max_new=MAX_NEW)
        print(f"  {name:14s} params {out[name]['stored_params']:>12,}  "
              f"peak {out[name]['peak_mem_gb']:>6.2f} GB  {out[name]['tokens_per_s']:>8.1f} tok/s")
        del model; gc.collect(); torch.cuda.empty_cache()

    # The router is the comparison the paper's cost defence rests on, so it cannot be omitted:
    # it holds EVERY expert resident and runs a gate per token, where the merge ships one
    # adapter the size of a single LoRA.
    gate_p = ROOT/f"runs/mole/{m}/python/routerlora_{SHORT[m]}_s17/gate.pt"
    if gate_p.exists():
        try:
            from obtune.mole.model import build_mole_model
            paths = {c: str(root/f"{c}_r32_s17"/"best") for c in EXPERTS
                     if (root/f"{c}_r32_s17"/"best").exists()}
            gc.collect(); torch.cuda.empty_cache(); torch.cuda.reset_peak_memory_stats()
            # gate.pt is {"gate": <state_dict>, "summary": {...}} -- passing the outer dict
            # to load_state_dict fails with a missing-keys RuntimeError, which is what the
            # first run hit.
            _ck = torch.load(gate_p, map_location="cpu")
            gate_sd = _ck["gate"] if isinstance(_ck, dict) and "gate" in _ck else _ck
            holder = build_mole_model(m, paths, d_router=64, shared_query=False, device_map="cuda")
            holder.gate.load_state_dict(gate_sd)
            holder.model.eval()
            stored = sum(_params(root/f"{c}_r32_s17"/"best") for c in paths)
            stored += sum(t.numel() for t in gate_sd.values() if hasattr(t, "numel"))
            out["router"] = dict(stored_params=stored, n_experts=len(paths),
                                 peak_mem_gb=round(torch.cuda.max_memory_allocated()/2**30, 2),
                                 tokens_per_s=round(timed(holder.model), 1),
                                 n_prompts=N_PROMPTS, max_new=MAX_NEW)
            print(f"  {'router':14s} params {stored:>12,}  "
                  f"peak {out['router']['peak_mem_gb']:>6.2f} GB  "
                  f"{out['router']['tokens_per_s']:>8.1f} tok/s  ({len(paths)} experts)")
            del holder; gc.collect(); torch.cuda.empty_cache()
        except Exception as e:
            out["router"] = {"error": f"{type(e).__name__}: {e}"}
            print(f"  router FAILED: {type(e).__name__}: {e}")
    else:
        print(f"  router: no gate at {gate_p}")

    f = ROOT/f"results/analysis/pipeline/deployment_cost_{m}.json"
    f.write_text(json.dumps(out, indent=2)); print(f"wrote {f}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
