#!/usr/bin/env python
"""B10 retention table for the paper: general coding ability after adaptation. No GPU.

    python scripts/analysis/86_retention_table.py

Reads results/retention/*.json (written by obtune.bench_retention, rescored by
85_rescore_retention.py) and emits one LaTeX table into paper/final/tables/ and
paper/router_merger/tables/, plus the summary numbers the prose quotes.

DESIGN CHOICES, with the reasons:
  * MBPP+ only in the table. It is 0/399 in our corpus; HumanEval is one of the corpus's
    sources (74/164 problems in the train split), so its arms-vs-base contrast is biased toward
    the arms. HumanEval+ is summarised in the printout for the text, not tabulated.
  * Both merge operators. The paper's Merge is DARE-TIES; plain TIES is the A5 operator
    comparison's other arm. They part company here, so showing only one would misstate either
    "merging preserves coding ability" or its failure.
  * Colour threshold 1.5 points, not "any difference". The untuned model -- no training seed
    involved -- differed by up to 1.3 points between two runs of the same cell (seed-42
    replication, 2026-09-25), so smaller gaps are evaluation noise, not retention.
  * A dagger marks cells where >= 50 % of replies contain no function at all: the arm answered
    in another format (often a bare predicted value), which is a different failure from writing
    wrong code, and the reader should be able to tell them apart.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "results" / "retention"

MODELS = ["codellama-7b", "codellama-13b", "codellama-34b", "llama31-8b",
          "starcoder2-15b", "gemma3-12b", "codegemma-7b", "granite31-8b"]
NICE = {"codellama-7b": "CodeLlama-7B", "codellama-13b": "CodeLlama-13B",
        "codellama-34b": "CodeLlama-34B", "llama31-8b": "Llama-3.1-8B",
        "starcoder2-15b": "StarCoder2-15B", "gemma3-12b": "Gemma-3-12B",
        "codegemma-7b": "CodeGemma-7B", "granite31-8b": "Granite-3.1-8B"}
ARMS = [("Base", "base"), ("ICL", "icl_k4"), ("Clean", "tuned_L0"), ("Breadth", "mono_all"),
        ("KL", "cons_lam3"), ("Router", "mole_router"), ("Merge", "merge_dare_ties"),
        ("TIES", "merge_ties")]
NOISE = 1.5       # points; see module docstring
NODEF = 0.5       # dagger threshold on raw_no_def_rate


def load(bench: str, model: str, arm: str, root: Path = RES):
    f = root / f"{bench}_{model}_{arm}.json"
    return json.loads(f.read_text()) if f.exists() else None


def cell(d, base):
    if d is None:
        return r"\texttt{--}"
    v = 100 * d["pass@1_plus"]
    s = f"{v:.1f}"
    if (d.get("raw_no_def_rate") or 0) >= NODEF:
        s += r"$^\dagger$"
    if base is not None and d is not base:
        b = 100 * base["pass@1_plus"]
        if v > b + NOISE:
            s = r"\textcolor{green!55!black}{" + s + "}"
        elif v < b - NOISE:
            s = r"\textcolor{red!70!black}{" + s + "}"
    return s


def main() -> int:
    L = [r"% GENERATED by scripts/analysis/86_retention_table.py -- do not edit by hand.",
         r"\begin{table*}[t]", r"\centering\small\setlength{\tabcolsep}{4pt}",
         r"\caption{\textbf{General coding ability after adaptation.} MBPP+ pass@1 (\%, the "
         r"extended test suite), greedy decoding, 399 tasks, none of which occur in our training "
         r"data. Green and red denote more than " + f"{NOISE:g}" + r" points above and below the "
         r"untuned model; smaller differences are within the run-to-run variation of the untuned "
         r"model itself. $^\dagger$: at least half of the replies contain no function, typically "
         r"because the model answers with a predicted value. \emph{Merge} is the paper's "
         r"DARE-TIES merge; \emph{TIES} is the same specialists merged without random dropping.}",
         r"\label{tab:retention}",
         r"\begin{tabular}{@{}l" + "r" * len(ARMS) + r"@{}}", r"\toprule",
         r"\textbf{Model} & " + " & ".join(r"\textbf{%s}" % a for a, _ in ARMS) + r" \\",
         r"\midrule"]
    missing = []
    for m in MODELS:
        base = load("mbppplus", m, "base")
        row = [NICE[m]]
        for _, arm in ARMS:
            d = load("mbppplus", m, arm)
            if d is None:
                missing.append(f"mbppplus_{m}_{arm}")
            row.append(cell(d, base))
        L.append(" & ".join(row) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    for d in ("final", "router_merger"):
        f = ROOT / f"paper/{d}/tables/retention.tex"
        f.write_text("\n".join(L) + "\n")
        print(f"wrote {f.relative_to(ROOT)}")
    if missing:
        print("MISSING:", ", ".join(missing))

    # ---- the numbers the prose quotes -------------------------------------------------
    for bench in ("mbppplus", "humanevalplus"):
        print(f"\n{bench}: arm - base (points); count below base by > {NOISE:g}")
        for lab, arm in ARMS[1:]:
            ds = []
            for m in MODELS:
                b, d = load(bench, m, "base"), load(bench, m, arm)
                if b and d:
                    ds.append(100 * (d["pass@1_plus"] - b["pass@1_plus"]))
            below = sum(x < -NOISE for x in ds)
            print(f"  {lab:8s} min {min(ds):+6.1f}  max {max(ds):+6.1f}  below {below}/{len(ds)}")

    print("\nseed 42 vs seed 17 (MBPP+, HumanEval+): arm - base, points")
    for m in ("codellama-7b", "llama31-8b", "granite31-8b"):
        for bench in ("mbppplus", "humanevalplus"):
            out = []
            for lab, arm in ARMS:
                if arm in ("base", "icl_k4", "mole_router"):
                    continue
                r = []
                for root in (RES, RES / "seed42"):
                    b, d = load(bench, m, "base", root), load(bench, m, arm, root)
                    r.append("--" if not (b and d) else f"{100*(d['pass@1_plus']-b['pass@1_plus']):+.1f}")
                out.append(f"{lab} {r[0]}/{r[1]}")
            print(f"  {m:14s} {bench:14s} " + "  ".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
