#!/usr/bin/env bash
# Rank sweep — is "breadth hurts" a capacity limit, or a fact about breadth?
#
# Gate 0 found the all-conditions adapter BELOW the clean-code control on the held-out
# obfuscator (-2.9 pts, CI [-5.2,-0.7]). Its checkpoint curve was flat, so it was not
# undertrained on steps — but that is equally consistent with a capacity ceiling: the
# control spends LoRA rank 32 on one condition, mono spends the same 32 on six.
#
# Four arms, run two at a time across the two GPUs given:
#   mono r=64, r=128   does more capacity close the gap at all?
#   mono r=192         parameter-matched to six r=32 specialists — the fair comparison
#   L0 control r=64    does rank help the control too? (if so, capacity helps
#                      everything and says nothing specific about breadth)
#
# setsid, not tmux: the tmux server on this host has died twice mid-run and taken every
# orchestrator with it. Idempotent — finished arms are skipped on re-run.
#
#   bash scripts/run_rank_sweep.sh 0 1
set -uo pipefail
cd "$(dirname "$0")/.."
source scripts/env.sh

GPU_A="${1:-0}"
GPU_B="${2:-1}"
LOG=runs/logs/rank_sweep.log
export OBTUNE_GPU_MEM_UTIL="${OBTUNE_GPU_MEM_UTIL:-0.45}"
mkdir -p runs/logs results/analysis

say() { echo "[$(date -u +%F' '%H:%M:%S)] $*" | tee -a "$LOG"; }

# config : adapter-dir : eval-system-name
ARMS=(
  "train/rank_mono_r64.yaml:L0-L1b-L1r-L2-S1-S2_r64_s17:mono_r64"
  "train/rank_mono_r128.yaml:L0-L1b-L1r-L2-S1-S2_r128_s17:mono_r128"
  "train/rank_mono_r192.yaml:L0-L1b-L1r-L2-S1-S2_r192_s17:mono_r192"
  "train/rank_l0_r64.yaml:L0_r64_s17:ctl_r64"
)
ADAPTERS=runs/adapters/qwen25c-1.5b/python

train_arm() {  # $1 = config, $2 = adapter dir name, $3 = gpu
  if [ -d "$ADAPTERS/$2/final" ]; then say "$2 already trained"; return 0; fi
  say "training $2 on GPU $3"
  CUDA_VISIBLE_DEVICES="$3" python -m obtune.train_sft --config "$1" \
    >> "runs/logs/rank_$2.log" 2>&1 || { say "WARN: training failed for $2"; return 1; }
  say "$2 trained"
}

say "=== rank sweep start (GPUs $GPU_A, $GPU_B) ==="

# Two at a time, so each arm gets a whole GPU rather than contending.
i=0
while [ $i -lt ${#ARMS[@]} ]; do
  a="${ARMS[$i]}"; b="${ARMS[$((i+1))]:-}"
  cfg_a="${a%%:*}"; rest_a="${a#*:}"; dir_a="${rest_a%%:*}"
  train_arm "$cfg_a" "$dir_a" "$GPU_A" &
  pid_a=$!
  if [ -n "$b" ]; then
    cfg_b="${b%%:*}"; rest_b="${b#*:}"; dir_b="${rest_b%%:*}"
    train_arm "$cfg_b" "$dir_b" "$GPU_B" &
    pid_b=$!
    wait $pid_b
  fi
  wait $pid_a
  i=$((i+2))
done

say "=== all arms trained; evaluating ==="

# One epoch means one checkpoint, so there is nothing for ckpt-select to choose:
# `final` IS the selected checkpoint. Point `best` at it so the eval configs and the
# adapter-path convention keep working unchanged.
for a in "${ARMS[@]}"; do
  rest="${a#*:}"; dir="${rest%%:*}"
  [ -e "$ADAPTERS/$dir/best" ] || ln -sfn "$PWD/$ADAPTERS/$dir/final" "$ADAPTERS/$dir/best"
done

# Build the eval config from the arms that actually trained.
{
  echo "# Generated by scripts/run_rank_sweep.sh — do not edit by hand."
  echo "_extends: _base_eval.yaml"
  echo "phase: main"
  echo "model: qwen25c-1.5b"
  echo "language: python"
  echo "eval_source: heldout"
  echo "engine:"
  # The whole point of this sweep is adapters ABOVE the default rank; the engine cap
  # (64 in _base_eval.yaml) rejected r=128/192 and killed the eval after one cell.
  # vLLM only accepts specific values (1,8,16,32,64,128,256,320,512) — 192 is NOT one
  # of them, so the cap is the next allowed value above our largest adapter rank.
  echo "  max_lora_rank: 256"
  echo "systems:"
  for a in "${ARMS[@]}"; do
    rest="${a#*:}"; dir="${rest%%:*}"; name="${rest#*:}"
    arch="mono"; [ "$name" = "ctl_r64" ] && arch="per_type"
    tc="mix"; [ "$name" = "ctl_r64" ] && tc="L0"
    [ -e "$ADAPTERS/$dir/best" ] && \
      echo "  - {name: $name, adapter: \"$ADAPTERS/$dir/best\", arch: $arch, train_cond: $tc}"
  done
  echo "eval_conditions: [L0, L1b, L1r, L2, S1, S2, H1]"
  echo "h1_access_purpose: final_eval"
} > configs/eval/rank_sweep.yaml

say "evaluating all arms on GPU $GPU_A"
CUDA_VISIBLE_DEVICES="$GPU_A" python -m obtune.eval_vllm --config eval/rank_sweep.yaml \
  >> "$LOG" 2>&1 || say "WARN: rank-sweep eval failed"

say "=== collating ==="
python -m obtune.trial_table >> "$LOG" 2>&1
python - <<'PY' 2>&1 | tee -a "$LOG"
import json, sys
sys.path.insert(0, "src")
import pandas as pd
from obtune.control_relative import bootstrap_delta

df = pd.read_parquet("results/trials.parquet")
df = df[(df.language == "python") & (df.phase == "main")]
cells = df.groupby(["adapter_id", "eval_cond"])["snippet_id"].apply(set)
if not len(cells):
    print("no cells"); raise SystemExit(0)
d = df[df.snippet_id.isin(set.intersection(*cells.tolist()))]

def by_adapter(sub: str, cond: str):
    return d[d.adapter_id.astype(str).str.contains(sub, na=False) & (d.eval_cond == cond)]

conds = [c for c in ["L0","L1b","L1r","L2","S1","S2","H1"] if c in set(d.eval_cond)]
arms = [("mono r32 (gate)", "L0-L1b-L1r-L2-S1-S2_r32"), ("mono r64", "_r64_s17"),
        ("mono r128", "_r128_s17"), ("mono r192", "_r192_s17")]
ctl32 = lambda c: d[d.adapter_id.astype(str).str.contains("/L0_r32_s17", na=False) & (d.eval_cond == c)]

print(f"\nprograms: {d.snippet_id.nunique()}   trials: {len(d)}\n")
print(f"{'arm':18}" + "".join(f"{c:>8}" for c in conds))
for label, sub in arms:
    row = [by_adapter(sub, c) for c in conds]
    if not any(len(r) for r in row):
        continue
    print(f"{label:18}" + "".join(f"{r.correct.mean():8.3f}" if len(r) else f"{'--':>8}" for r in row))

# Everything is reported against the L0-ONLY control, on every condition — not just
# H1. Raw accuracy cannot separate "learned the task" from "learned obfuscation", and
# an H1-only view hides where breadth genuinely does pay (it pays on exactly one
# condition). The control's own rank arm is included as the noise floor: if it moves,
# the differences below are not readable.
# The control appears as its own row (zeros by construction) so a reader never has to
# infer what the deltas are measured against, and as an r=64 arm so the noise floor is
# visible in the same table.
all_arms = [("ctl r32 (ref)", "/L0_r32_s17")] + arms + [("ctl r64", "/L0_r64_s17")]
print("\nDelta vs the L0-only control (r=32), accuracy points; * = CI excludes 0")
print(f"{'arm':18}" + "".join(f"{c:>10}" for c in conds))
out = {"_control": "L0-only adapter, r=32", "per_condition": {}, "h1": {}}
for label, sub in all_arms:
    cells_out, row = {}, []
    for c in conds:
        t, k = by_adapter(sub, c), ctl32(c)
        if not len(t) or not len(k):
            row.append(f"{'--':>10}"); continue
        con = bootstrap_delta(t, k, f"{label}:{c}", n_resamples=2000,
                              eq_margin=(4.0 if c == "H1" else 3.0))
        cells_out[c] = con.to_dict()
        row.append(f"{con.value_pts:>9.1f}{'*' if con.excludes_zero else ' '}")
    if cells_out:
        out["per_condition"][label] = cells_out
        print(f"{label:18}" + "".join(row))

print("\nH1 vs the L0-only control (the capacity test):")
print(f"{'arm':18}{'delta':>9}{'CI95':>20}{'verdict':>16}")
for label, sub in arms:
    t, c = by_adapter(sub, "H1"), ctl32("H1")
    if not len(t) or not len(c):
        continue
    con = bootstrap_delta(t, c, label, n_resamples=4000, eq_margin=4.0)
    out["h1"][label] = con.to_dict()
    print(f"{label:18}{con.value_pts:>+9.1f}"
          f"{f'[{con.ci_lo:+.1f},{con.ci_hi:+.1f}]':>20}{con.verdict:>16}")
json.dump(out, open("results/analysis/rank_sweep.json", "w"), indent=2)
print("\nIf the gap closes as rank rises, 'breadth hurts' was a capacity limit.")
print("If r=192 (parameter-matched to six r=32 specialists) still trails, it was not.")
PY
say "=== rank sweep complete — results/analysis/rank_sweep.json ==="
