#!/usr/bin/env python
"""Emit every LaTeX results table in paper/ from the result files, never from a report.

    python scripts/paper/gen_tables.py

HOUSE RULE, inherited from paper_modularity/main.tex and kept deliberately: **no number is typed
into a .tex by hand.** Each table below is generated from a JSON under `results/analysis/`, which
is itself generated from the per-cell parquets. The reports in `docs/` and `MASTER_REPORT.md` are
an index of where to look, not a source; where a report and a result file disagree, the file wins.

Every emitted file carries a header naming the JSON it came from and the generating script, so a
table in the paper can be traced back to a cell in two hops.

A missing input is NOT filled in and is NOT skipped silently: the table emits \\pending in the
affected cells and the script reports it on stderr, so `make audit` (grep for \\pending) still
sees the hole.
"""
from __future__ import annotations

import datetime as dt
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "results" / "analysis"
OUT = ROOT / "paper" / "tables"
PENDING = r"\pending"


def load(rel: str):
    p = RES / rel
    if not p.exists():
        print(f"  MISSING INPUT: {p.relative_to(ROOT)}", file=sys.stderr)
        return None
    return json.loads(p.read_text())


def ci(d, key="value_pts", lo="ci_lo", hi="ci_hi", star=True, prec=2):
    """A point estimate with its interval, bolded when it excludes zero."""
    if d is None:
        return PENDING
    v, l, h = d.get(key), d.get(lo), d.get(hi)
    if v is None:
        return PENDING
    body = f"${v:+.{prec}f}$ \\tiny[{l:+.{prec}f}, {h:+.{prec}f}]"
    sig = d.get("excludes_zero")
    if sig is None:
        sig = (l is not None and h is not None and (l > 0 or h < 0))
    return f"\\textbf{{{body}}}" if (star and sig) else body


def write(name: str, body: str, source: str, caption: str, label: str):
    hdr = (f"% GENERATED by scripts/paper/gen_tables.py on "
           f"{dt.datetime.now(dt.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n"
           f"% SOURCE: {source}\n"
           f"% Do not edit by hand -- regenerate. Numbers come from result files, never from a report.\n")
    (OUT / name).write_text(hdr + body)
    print(f"  wrote paper/tables/{name}")


# --------------------------------------------------------------------------- #
LINEAGE = {"codellama-7b": "Meta", "codellama-13b": "Meta", "codellama-34b": "Meta",
           "llama31-8b": "Meta", "starcoder2-15b": "BigCode", "gemma3-12b": "Google",
           "codegemma-7b": "Google", "granite31-8b": "IBM"}
NICE = {"codellama-7b": "CodeLlama-7B", "codellama-13b": "CodeLlama-13B",
        "codellama-34b": "CodeLlama-34B", "llama31-8b": "Llama-3.1-8B",
        "starcoder2-15b": "StarCoder2-15B", "gemma3-12b": "Gemma-3-12B",
        "codegemma-7b": "CodeGemma-7B", "granite31-8b": "Granite-3.1-8B"}
ORDER = ["codellama-7b", "codellama-13b", "codellama-34b", "llama31-8b",
         "starcoder2-15b", "gemma3-12b", "codegemma-7b", "granite31-8b"]
# \vok / \vrefuted / \vinc -- NOT \ref, which is LaTeX's own cross-reference command.
MARK = {"REPLICATED": r"\vok", "REFUTED": r"\vrefuted", "INCONCLUSIVE": r"\vinc"}


def t_panel():
    d = load("panel_replication_final.json")
    rows, tally = [], {r: {} for r in ("R1", "R2", "R3")}
    for m in ORDER:
        e = (d or {}).get(m)
        if not e:
            rows.append(f"{NICE[m]} & {LINEAGE[m]} & {PENDING} & {PENDING} & {PENDING} \\\\")
            continue
        cells = []
        for r in ("R1", "R2", "R3"):
            x = e[r]
            x = {**x, "value_pts": x["delta_pts"]}
            v = e[r]["verdict"]
            tally[r][v] = tally[r].get(v, 0) + 1
            cells.append(ci(x) + " " + MARK.get(v, ""))
        rows.append(f"{NICE[m]} & {LINEAGE[m]} & " + " & ".join(cells) + " \\\\")
    tal = " & ".join(
        f"{t.get('REPLICATED',0)}/{t.get('INCONCLUSIVE',0)}/{t.get('REFUTED',0)}"
        for t in (tally["R1"], tally["R2"], tally["R3"]))
    body = (r"""\begin{tabular}{llccc}
\toprule
model & lineage & \textbf{R1} $\Delta_{\mathrm{breadth}}$ & \textbf{R2} $\Delta_{\mathrm{anchor}}$ & \textbf{R3} $\Delta_{\mathrm{clean}}$ \\
 & & \textsc{mono}$-$\textsc{clean} @X1 & \textsc{cons}$-$\textsc{mono} @X1 & \textsc{cons}$-$\textsc{clean} @L0 \\
\midrule
""" + "\n".join(rows) + r"""
\midrule
\multicolumn{2}{l}{\emph{replicated / inconclusive / refuted}} & """ + tal + r""" \\
\bottomrule
\end{tabular}""")
    write("panel_replication.tex", body, "results/analysis/panel_replication_final.json",
          "eight-model replication", "tab:panel")


def t_grid():
    d = load("pipeline/grid_agreement_panel_core.json")
    rows = []
    for m in ORDER[:4]:
        e = ((d or {}).get("models") or {}).get(m)
        if not e:
            rows.append(f"{NICE[m]} & {PENDING} & {PENDING} & {PENDING} & {PENDING} \\\\")
            continue
        cells, worst = [], 0.0
        for r in ("R1", "R2", "R3"):
            x = e[r]
            worst = max(worst, x["abs_delta"])
            cells.append(f"${x['published']:+.2f} \\rightarrow {x['uniform']:+.2f}$")
        rows.append(f"{NICE[m]} & " + " & ".join(cells) + f" & {worst:.2f} \\\\")
    body = (r"""\begin{tabular}{lcccc}
\toprule
model & R1 pub.\ $\rightarrow$ grid & R2 pub.\ $\rightarrow$ grid & R3 pub.\ $\rightarrow$ grid & max $|\Delta|$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")
    write("grid_agreement.tex", body, "results/analysis/pipeline/grid_agreement_panel_core.json",
          "grid agreement", "tab:grid")


def t_ladder():
    d = load("pipeline/f2_divergence_codellama7b.json")
    dep = load("pipeline/composite_depth_codellama7b.json")
    d0 = (dep or {}).get("ref_depth2", {}).get("mono_all - tuned_L0")
    d1 = (dep or {}).get("pooled", {}).get("mono_all - tuned_L0")
    d1c = (dep or {}).get("pooled", {}).get("cons_lam3 - tuned_L0")
    d1v = (dep or {}).get("pooled", {}).get("cons_lam3 - mono_all")
    lv = (d or {}).get("by_level", {})
    rows = [
        r"d0 & depth 2, all seen & " + ci(d0) + " & " + PENDING + " & " + PENDING + r" \\",
        r"d1 & depth 3--4, all seen & " + ci(d1) + " & " + ci(d1c) + " & " + ci(d1v) + r" \\",
        r"\midrule",
        r"\textbf{d2} & depth 2, \textbf{unseen inside} & " + ci(lv.get("d2", {}).get("mono_all - tuned_L0"))
        + " & " + ci(lv.get("d2", {}).get("cons_lam3 - tuned_L0"))
        + " & " + ci(lv.get("d2", {}).get("cons_lam3 - mono_all")) + r" \\",
        r"\textbf{d3} & depth 3, \textbf{unseen inside} & " + ci(lv.get("d3", {}).get("mono_all - tuned_L0"))
        + " & " + ci(lv.get("d3", {}).get("cons_lam3 - tuned_L0"))
        + " & " + ci(lv.get("d3", {}).get("cons_lam3 - mono_all")) + r" \\",
    ]
    body = (r"""\begin{tabular}{llccc}
\toprule
level & stimulus & \textsc{mono}$-$\textsc{clean} & \textsc{cons}$-$\textsc{clean} & \textsc{cons}$-$\textsc{mono} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")
    write("divergence_ladder.tex", body,
          "results/analysis/pipeline/{f2_divergence_codellama7b,composite_depth_codellama7b}.json",
          "divergence ladder", "tab:ladder")


def t_split():
    d = load("pipeline/f2_divergence_codellama7b.json")
    parts = {"C_L1r_X1": "ident.\\ $\\to$ unseen", "C_L1r_X1m": "ident.\\ $\\to$ unseen (MBA half)",
             "C3_L1r_S1_X1": "ident.\\ $\\to$ struct.\\ $\\to$ unseen",
             "C_S2_X1": "struct.\\ $\\to$ unseen", "C_S1_X1s": "struct.\\ $\\to$ unseen (str.\\ half)",
             "C_X1_S1": "unseen $\\to$ struct."}
    pc = (d or {}).get("per_composite", {})
    rows = [f"\\texttt{{{k.replace('_', chr(92)+'_')}}} & {v} & "
            + ci(pc.get(k, {}).get("mono_all - tuned_L0")) + r" \\" for k, v in parts.items()]
    f3 = load("pipeline/f3a_stack_identifier_f2_unseen_codellama7b.json")
    f3s = load("pipeline/f3a_stack_identifier_depth_seen_codellama7b.json")
    extra = []
    for lbl, src in (("stacks containing the unseen family", f3), ("all-seen depth-3/4 stacks", f3s)):
        p = (src or {}).get("pooled", {})
        extra.append(f"\\multicolumn{{2}}{{l}}{{\\emph{{{lbl}}}: identifier $-$ structural}} & "
                     + ci(p.get("difference_of_differences")) + r" \\")
    body = (r"""\begin{tabular}{llc}
\toprule
composite & composition & \textsc{mono}$-$\textsc{clean} \\
\midrule
""" + "\n".join(rows) + "\n\\midrule\n" + "\n".join(extra) + r"""
\bottomrule
\end{tabular}""")
    write("identifier_split.tex", body,
          "results/analysis/pipeline/{f2_divergence_codellama7b,f3a_stack_identifier_*}.json",
          "identifier split", "tab:split")


def t_models():
    files = {"codellama-7b": "pipeline/f2_divergence_codellama7b.json"}
    for m in ("gemma3-12b", "starcoder2-15b", "granite31-8b", "codegemma-7b",
              "codellama-13b", "codellama-34b", "llama31-8b"):
        files[m] = f"pipeline/f2_divergence_core_{m.replace('-', '')}.json"
    rows = []
    for m in ORDER:
        d = load(files[m]) if (RES / files[m]).exists() else None
        if d is None:
            rows.append(f"{NICE[m]} & {LINEAGE[m]} & {PENDING} & {PENDING} & {PENDING} \\\\")
            continue
        b = d["by_level"]["d2"]
        rows.append(f"{NICE[m]} & {LINEAGE[m]} & " + ci(b["cons_lam3 - mono_all"]) + " & "
                    + ci(b["cons_lam3 - tuned_L0"]) + " & " + ci(b["tuned_X1 - tuned_L0"]) + r" \\")
    body = (r"""\begin{tabular}{llccc}
\toprule
model & lineage & \textsc{cons}$-$\textsc{mono} & \textsc{cons}$-$\textsc{clean} & \textsc{fam}$-$\textsc{clean} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")
    write("divergence_by_model.tex", body,
          "results/analysis/pipeline/f2_divergence{,_core}_*.json",
          "divergence by model", "tab:divmodels")


def t_dissociation():
    """RQ1's headline: the seen/unseen stack difference, WITHIN model, on one program set."""
    d = load("pipeline/stack_dissociation.json")
    ms = (d or {}).get("models", {})
    rows, n = [], None
    for m in ORDER:
        e = ms.get(m)
        if not e:
            rows.append(f"{NICE[m]} & {LINEAGE[m]} & {PENDING} & {PENDING} & {PENDING}" + r" \\")
            continue
        n = e["n_programs"]
        rows.append(f"{NICE[m]} & {LINEAGE[m]} & " + ci(e["seen"]) + " & "
                    + ci(e["unseen_containing"]) + " & " + ci(e["difference"]) + r" \\")
    tal = (d or {}).get("tally", {})
    foot = (f"\\multicolumn{{4}}{{l}}{{\\emph{{difference significant on}}}} & "
            f"{tal.get('difference_significant','?')} of {tal.get('models_read','?')} read \\\\"
            if tal else "")
    body = (r"""\begin{tabular}{llccc}
\toprule
model & lineage & seen stacks & unseen inside & \textbf{difference} \\
\midrule
""" + "\n".join(rows) + ("\n\\midrule\n" + foot if foot else "") + r"""
\bottomrule
\end{tabular}""")
    write("stack_dissociation.tex", body, "results/analysis/pipeline/stack_dissociation.json",
          "stack dissociation", "tab:dissoc")


def t_geometry():
    banks = [("5 specialists, one seed", "condition only", "spec_s17"),
             ("clean-code arm, 3 seeds", "seed only", "L0_crossseed"),
             ("5 specialists $\\times$ 2 seeds", "both", "spec_crossseed")]
    rows = []
    for lbl, varies, tag in banks:
        p = RES / f"f1b/geometry_codellama7b_{tag}.json"
        if not p.exists():
            rows.append(f"{lbl} & {varies} & {PENDING} & {PENDING} & {PENDING} \\\\")
            continue
        e = list(json.loads(p.read_text())["epochs"].values())[0]
        rows.append(f"{lbl} & {varies} & {e['cosine_mean']:.3f} & "
                    f"{e['sign_conflict_mean']:.3f} & {e['ties_keep_mean']:.3f} \\\\")
    body = (r"""\begin{tabular}{llccc}
\toprule
adapter bank & what varies & mean cosine & sign conflict & TIES kept \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")
    write("geometry.tex", body, "results/analysis/f1b/geometry_codellama7b_*.json",
          "task-vector geometry", "tab:geom")


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for f in (t_panel, t_grid, t_ladder, t_split, t_models, t_dissociation, t_geometry):
        f()
    n = sum(PENDING in (OUT / p.name).read_text() for p in OUT.glob("*.tex"))
    print(f"\n{len(list(OUT.glob('*.tex')))} tables; {n} contain \\pending (holes are visible, not filled)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
